services:
  # On ne redéfinit ici que ce qui change pour le backend en mode DEV

  backend:
    # on monte le code source local dans /app (pour live-reload)
    volumes:
      - ./subly-back:/app
      - /app/node_modules

    # on remplace la commande de démarrage par le “watch mode” de NestJS
    command: >
      sh -c "npm install && npm run seed && npm run start:dev"

    # on précise que, en dev, on veut NODE_ENV=development
    environment:
      NODE_ENV: development